# 定义通用资源配置
x-resource-config: &resource-config
  deploy:
    resources:
      limits:
        memory: ${DOCKER_MEMORY_LIMIT:-3584M}
        cpus: '${DOCKER_CPU_LIMIT:-1.0}'
      reservations:
        memory: ${DOCKER_MEMORY_RESERVATION:-512M}

services:
  # Redis 缓存服务
  redis:
    image: registry.ap-southeast-1.aliyuncs.com/fastbuildai/redis:8.0.2
    container_name: fastbuildai-redis${DOCKER_CONTAINER_SUFFIX}
    restart: always
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      QUICK_START_MODE: ${QUICK_START_MODE:-false}
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - fastbuildai-network
    <<: *resource-config
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL 数据库服务 (with pgvector)
  postgres:
    image: registry.ap-southeast-1.aliyuncs.com/fastbuildai/postgres:17.5-amd64
    container_name: fastbuildai-postgres${DOCKER_CONTAINER_SUFFIX}
    restart: always
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - ./data/postgres/postgres_data:/var/lib/postgresql/data
    networks:
      - fastbuildai-network
    <<: *resource-config
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js 开发环境
  nodejs:
    image: registry.ap-southeast-1.aliyuncs.com/fastbuildai/node:22.14.0-alpine
    container_name: fastbuildai-nodejs${DOCKER_CONTAINER_SUFFIX}
    restart: unless-stopped
    working_dir: /fastbuildai
    volumes:
      - ../:/fastbuildai
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: ${SERVER_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: |
      sh -c '
      set -e
      echo "🚀 Starting FastbuildAI container..."
      echo "🔍 Debug: QUICK_START_MODE = [$QUICK_START_MODE]"
      npm install -g pnpm
      
      if [ ! -d "./node_modules" ] || [ "$QUICK_START_MODE" = "false" ]; then
        rm -rf ./node_modules
        echo "🧹 Cleaning node_modules (QUICK_START_MODE=false)..."
        pnpm i
        echo "📦 Installing dependencies..."
      fi
      
      if [ ! -d "./public" ] || [ "$QUICK_START_MODE" = "false" ]; then
        pnpm --filter ./apps/web run generate
        echo "🌐 Building web application..."
      fi
      
      if [ ! -d "./apps/server/dist" ] || [ "$QUICK_START_MODE" = "false" ]; then
        pnpm --filter ./apps/server run build
        echo "🔧 Building server application..."
      fi
      
      echo "🎯 Starting production server..."
      exec pnpm --filter ./apps/server run start:prod
      '
    networks:
      - fastbuildai-network
    <<: *resource-config
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'dist/main' | grep -v grep || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 180s

networks:
  fastbuildai-network:
    driver: bridge